### ISSUE TITLE
Não está aparecendo os agendados no Integrator mais.

### ISSUE THREAD

**Issue by Ezelki** [wrGGsiq/scriptsGG#5]
Teste

**Comment by wrGGsiq** [comment]
Eu percebi, fiz a conexão com uma API que eu fiz, só que como o serviço era
gratuito, expirou muito cedo.
Estou vendo outras formas.

**Comment by wrGGsiq** [comment]
A extensão voltou, só atualizar.

Aperta na extensão -> Utilitários -> Verificar Atualização de Scripts.

E depois dar um F5 no ISP, pode ser que ele peça permissão para o novo host, dai só aceitar.
